#!/bin/bash
shopt -s extglob nullglob

sourcesDir="/etc/apt/sources.list.d"

function ensureRepo() {
        REPO="$1"
        SUITES="$2"
        COMPONENTS="$3"
        REPONAME="$4"
        SOURCEFILE="$5"
        SOURCESPATH="$(dirname "${SOURCEFILE}")"
        if ( [ -z "$(echo "${SOURCESPATH}"/*.sources)" ] || ! grep -Fxq "URIs: ${REPO}" "${SOURCESPATH}"/*.sources ) && [ -n "$(echo "${SOURCESPATH}"/*.list)" ] && ! grep -q "^deb ${REPO} " "${SOURCESPATH}"/*.list ; then
                echo "Installing ${REPONAME} Repo"
                if [[ ! -s "${SOURCEFILE}" ]]; then
                        echo > "${SOURCEFILE}"
                fi
        sed -i.bak "1i\\
Types: deb\\
URIs: ${REPO}\\
Suites: ${SUITES}\\
Components: ${COMPONENTS}\\
" "${SOURCEFILE}"
        fi
}

function ensurePlainRepo() {
        ensureRepo "$1" "./" "" "$2" "$3"
}

function finish() {
        f="${1}"

        # No control fd: bail out
        [[ -z "${f}" || -z "${SILEO}" && -z "${CYDIA}" ]] && return
        if [[ -n "${SILEO}" ]]; then
                sileo=(${SILEO})
        else
                sileo=(${CYDIA})
        fi

        # Sileo control fd version < 1: bail out
        [[ ${sileo[1]} -ge 1 ]] || return

        echo "finish:${f}" >&${sileo[0]}
}

rm -f /etc/apt/sources.list.d/sileo.list
touch $sourcesDir/sileo.sources

if grep -Fxq "URIs: https://repounclutter.coolstar.org/" $sourcesDir/sileo.sources ;
then
	echo "Replaced BigBoss+ Repo with valid BigBoss repo"
	sed  '1{h;$!d} ; 1!{/./{H;$!d}}; x ; s;Types: deb\
URIs: https://repounclutter.coolstar.org/\
Suites: ./\
Components:.*;Types: deb\
URIs: http://apt.thebigboss.org/repofiles/cydia/\
Suites: stable\
Components: main;' $sourcesDir/sileo.sources
fi

if [ -f "/etc/apt/preferences.d/odyssey" ]; then
    rm "/etc/apt/preferences.d/odyssey"
fi

if [ -f "/etc/apt/preferences.d/chimera" ]; then
    rm "/etc/apt/preferences.d/chimera"
fi

ensureRepo http://apt.thebigboss.org/repofiles/cydia/ stable main BigBoss $sourcesDir/sileo.sources
ensurePlainRepo https://repo.chariz.com/ Chariz $sourcesDir/sileo.sources
ensurePlainRepo https://repo.dynastic.co/ Dynastic $sourcesDir/sileo.sources

if [ ! -f /etc/apt/sources.list.d/chimera.sources ] && [ ! -f /etc/apt/sources.list.d/electra.list ]; then
        ensurePlainRepo https://test.apt.bingner.com/ Elucubratus $sourcesDir/sileo-base.sources
fi

rm -f $sourcesDir/sileo.sources.bak 2> /dev/null || true
rm -f $sourcesDir/sileo-base.sources.bak 2> /dev/null || true

# be sure not to leave empty file with spaces if all the sources are already added elsewhere
if ! grep -q '^\s' $sourcesDir/sileo.sources; then
	echo -n > $sourcesDir/sileo.sources
fi

finish uicache

if [[ -z ${SILEO} && -z ${CYDIA} ]]; then
        echo "Not running in Package Manager. Trigger UICache"
        uicache -p /Applications/Sileo.app
fi

exit 0
