#!/bin/bash

if [ ! -f /etc/apt/sources.list.d/chimera.sources ] && [ ! -f /etc/apt/sources.list.d/electra.list ]; then
        sourcesDir="/etc/apt/sileo.list.d"
        mkdir -p $sourcesDir
        if [ -s /etc/apt/sources.list.d/sileo.sources ]; then
                mv /etc/apt/sources.list.d/sileo.sources $sourcesDir
                rm -f /etc/apt/sources.list.d/sileo-base.sources
        fi

        if ! grep -Fxq "Dir::Etc" /Applications/Sileo.app/sileo-apt.conf ;
then
        sed -i.bak '1s;^;Dir::Etc\
{\
        sourceparts "sileo.list.d/"\
}\
\
;' /Applications/Sileo.app/sileo-apt.conf
fi
rm -f /Applications/Sileo.app/sileo-apt.conf.bak 2> /dev/null || true

else
        sourcesDir="/etc/apt/sources.list.d"
fi

function ensureRepo() {
        REPO="$1"
        SUITES="$2"
        COMPONENTS="$3"
        REPONAME="$4"
        SOURCEFILE="$5"
        if [[ ! -s "${SOURCEFILE}" ]]; then
                echo > "${SOURCEFILE}"
        fi
        if ! grep -Fxq "URIs: ${REPO}" "${SOURCEFILE}"; then
                echo "Installing ${REPONAME} Repo"
        sed -i.bak "1i\\
Types: deb\\
URIs: ${REPO}\\
Suites: ${SUITES}\\
Components: ${COMPONENTS}\\
" "${SOURCEFILE}"
        fi
}

function ensurePlainRepo() {
        ensureRepo "$1" "./" "" "$2" "$3"
}

function finish() {
        f="${1}"

        # No control fd: bail out
        [[ -z "${f}" || -z "${SILEO}" && -z "${CYDIA}" ]] && return
        if [[ -n "${SILEO}" ]]; then
                sileo=(${SILEO})
        else
                sileo=(${CYDIA})
        fi

        # Sileo control fd version < 1: bail out
        [[ ${sileo[1]} -ge 1 ]] || return

        echo "finish:${f}" >&${sileo[0]}
}

rm /etc/apt/sources.list.d/sileo.list 2> /dev/null || true
touch $sourcesDir/sileo.sources

cr="\n"

if ! [ -s $sourcesDir/sileo.sources ]; then
	echo '' > $sourcesDir/sileo.sources
fi

if grep -Fxq "URIs: https://repounclutter.coolstar.org/" $sourcesDir/sileo.sources ;
then
	echo "Replaced BigBoss+ Repo with valid BigBoss repo"
	sed  '1{h;$!d} ; 1!{/./{H;$!d}}; x ; s;Types: deb\
URIs: https://repounclutter.coolstar.org/\
Suites: ./\
Components:.*;Types: deb\
URIs: http://apt.thebigboss.org/repofiles/cydia/\
Suites: stable\
Components: main;' $sourcesDir/sileo.sources
fi

ensureRepo http://apt.thebigboss.org/repofiles/cydia/ stable main BigBoss $sourcesDir/sileo.sources
ensurePlainRepo https://repo.chariz.com/ Chariz $sourcesDir/sileo.sources
ensurePlainRepo https://repo.dynastic.co/ Dynastic $sourcesDir/sileo.sources

if [ ! -f /etc/apt/sources.list.d/chimera.sources ] && [ ! -f /etc/apt/sources.list.d/electra.list ]; then
        ensurePlainRepo https://test.apt.bingner.com/ Elucubratus $sourcesDir/sileo-base.sources
fi

rm -f $sourcesDir/sileo.sources.bak 2> /dev/null || true
rm -f $sourcesDir/sileo-base.sources.bak 2> /dev/null || true

finish uicache

if [[ -z ${SILEO} && -z ${CYDIA} ]]; then
        echo "Not running in Package Manager. Trigger UICache"
        uicache -p /Applications/Sileo.app
fi

exit 0
